OS-7677. Use path as default dataset name and add default artifact description
hystax/optscale_arcee pull request #34
Opened 2024-07-11 06:27 UTC by nk-hystax

## Related issue number

OS-7677

## Checklist

* [ ] The pull request title is a good summary of the changes
* [ ] Unit tests for the changes exist
* [ ] New and existing unit tests pass locally

2024-07-11 12:56 UTC, artm-hx requested changes

2024-07-11 12:56 UTC, artm-hx commented on optscale_arcee/sender/sender.py
> +            description = f"Discovered in training " \
move to function?

2024-07-12 06:49 UTC, artm-hx approved these changes

2024-07-15 11:01 UTC, artm-hx approved these changes

2024-07-18 10:48 UTC, tm-hystax approved these changes

2024-07-18 10:48 UTC, merged