OS-6654 extended examples
hystax/optscale_arcee pull request #5
Opened 2023-08-31 06:42 UTC by artm-hx

added instrumentation-related things

2023-08-31 07:18 UTC, nk-hystax approved these changes

2023-09-28 06:27 UTC, nexusriot requested changes

2023-09-28 06:27 UTC, nexusriot commented on examples/s3_instrument.py
> +access_key_id = 'access_key_id'
I think it's reasonable to take that form env

2023-10-10 13:07 UTC, nexusriot approved these changes

2023-10-12 09:53 UTC, merged